DROP VIEW IF EXISTS BIS_VW_LINK_TIME;
DROP VIEW IF EXISTS BIS_VW_PRDT_TIME;
DROP VIEW IF EXISTS BIS_VW_ROUTE_BUS;

DROP TABLE IF EXISTS BIS_MT_GRP_CODE;
DROP TABLE IF EXISTS BIS_MT_DTL_CODE;

DROP TABLE IF EXISTS BIS_MT_BUS;
DROP TABLE IF EXISTS BIS_MT_BIT;

DROP TABLE IF EXISTS BIS_MT_ROUTE;
DROP TABLE IF EXISTS BIS_MT_NODE;
DROP TABLE IF EXISTS BIS_MT_STATION;
DROP TABLE IF EXISTS BIS_MT_LINK;

DROP TABLE IF EXISTS BIS_MT_ROUTE_PLAN;
DROP TABLE IF EXISTS BIS_MT_ROUTE_NODE;
DROP TABLE IF EXISTS BIS_MT_ROUTE_STATION;
DROP TABLE IF EXISTS BIS_MT_ROUTE_LINK;
DROP TABLE IF EXISTS BIS_MT_LINK_VERTEX;

DROP TABLE IF EXISTS BIS_MT_ALL_INFO;

DROP TABLE IF EXISTS BIS_HT_BUS_EVENT;

DROP TABLE IF EXISTS BIS_IT_LINK_SPEED;
DROP TABLE IF EXISTS BIS_IT_BUS_LOCATION;

DROP TABLE IF EXISTS BIS_HT_BUS_SERVICE;
DROP TABLE IF EXISTS BIS_HT_BIT_SERVICE;

CREATE TABLE BIS_MT_GRP_CODE (
	GROUP_CD VARCHAR(20) NOT NULL PRIMARY KEY,
	GROUP_NAME1 VARCHAR(30),
    GROUP_NAME2 VARCHAR(30)
);

CREATE TABLE BIS_MT_DTL_CODE (
	GROUP_CD VARCHAR(20),
	DETAIL_CD VARCHAR(3),
	DETAIL_NAME1 VARCHAR(30),
    DETAIL_NAME2 VARCHAR(30),
    PRIMARY KEY(GROUP_CD, DETAIL_CD)
);

CREATE TABLE BIS_MT_BUS (
	BUS_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	BUS_NAME VARCHAR(30),
    BUS_TYPE VARCHAR(3),
    IMP_ID VARCHAR(10),
    IMP_TYPE VARCHAR(3)
);

CREATE TABLE BIS_MT_BIT (
	STATION_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    STATION_NAME1 VARCHAR(30),
    STATION_NAME2 VARCHAR(30),
    STATION_TYPE VARCHAR(3),
    BIT_ID VARCHAR(10),
    BIT_TYPE VARCHAR(3),
    NODE_ID VARCHAR(10)
);

CREATE TABLE BIS_MT_ROUTE (
	ROUTE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    ROUTE_NAME1 VARCHAR(30),
    ROUTE_NAME2 VARCHAR(30),
    ROUTE_TYPE VARCHAR(3),
    ROUTE_LENGTH INT,
    RUN_TYPE VARCHAR(3),
    JOURNEY_TIME SMALLINT
);

CREATE TABLE BIS_MT_ROUTE_PLAN (
	ROUTE_ID VARCHAR(10),
    DAY_TYPE VARCHAR(3),
    SERVICE_COUNT SMALLINT,
    ST_FIRST_TIME VARCHAR(4),
    ST_LAST_TIME VARCHAR(4),
    ED_FIRST_TIME VARCHAR(4),
    ED_LAST_TIME VARCHAR(4),
    MIN_INTERVAL INT,
    MAX_INTERVAL INT,
    PRIMARY KEY(ROUTE_ID, DAY_TYPE)
);

CREATE TABLE BIS_MT_NODE (
	NODE_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NODE_NAME1 VARCHAR(30),
    NODE_NAME2 VARCHAR(30),
    NODE_TYPE VARCHAR(3),
	LAT DECIMAL(9,6),
	LON DECIMAL(9,6),
	IN_RADIUS SMALLINT,
	OUT_RADIUS SMALLINT
);

CREATE TABLE BIS_MT_STATION (
	STATION_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    STATION_NAME1 VARCHAR(30),
    STATION_NAME2 VARCHAR(30),
    STATION_TYPE VARCHAR(3),
    NODE_ID VARCHAR(10),
	LAT DECIMAL(9,6),
	LON DECIMAL(9,6)
);

CREATE TABLE BIS_MT_LINK (
	LINK_ID VARCHAR(10) NOT NULL PRIMARY KEY,
    LINK_NAME1 VARCHAR(30),
    LINK_NAME2 VARCHAR(30),
    LINK_TYPE VARCHAR(3),
    FROM_NODE_ID VARCHAR(10),
    TO_NODE_ID VARCHAR(10),
    LINK_LENGTH INT,
    LANE_COUNT SMALLINT,
    MAX_SPEED SMALLINT,
    IN_ANGLE SMALLINT,
    OUT_ANGLE SMALLINT
);

CREATE TABLE BIS_MT_LINK_VERTEX (
	LINK_ID VARCHAR(10),
    VERTEX_SEQ SMALLINT,
	LAT DECIMAL(9,6),
	LON DECIMAL(9,6),
	PRIMARY KEY(LINK_ID, VERTEX_SEQ)
);

CREATE TABLE BIS_MT_ALL_INFO (
	ROUTE_ID VARCHAR(10),
	ROUTE_TYPE VARCHAR(3),
    NODE_SEQ SMALLINT,
	NODE_ID VARCHAR(10),
	NODE_TYPE VARCHAR(3),
	LINK_SEQ SMALLINT,
	LINK_ID VARCHAR(10),
	LINK_TYPE VARCHAR(3),
	LINK_LENGTH SMALLINT,
    STATION_SEQ SMALLINT,
	STATION_ID VARCHAR(10),
	STATION_TYPE VARCHAR(3),
	BIT_ID VARCHAR(10),
	BIT_TYPE VARCHAR(3),
	PRIMARY KEY(ROUTE_ID, NODE_SEQ)
);

CREATE TABLE BIS_MT_ROUTE_NODE (
	ROUTE_ID VARCHAR(10),
    NODE_SEQ INT,
    NODE_ID VARCHAR(10),
    UPDOWN_DIR VARCHAR(3),
    PRIMARY KEY(ROUTE_ID, NODE_SEQ)
);

CREATE TABLE BIS_MT_ROUTE_STATION (
	ROUTE_ID VARCHAR(10),
    STATION_SEQ INT,
    STATION_ID VARCHAR(10),
    UPDOWN_DIR VARCHAR(3),
    PRIMARY KEY(ROUTE_ID, STATION_SEQ)
);

CREATE TABLE BIS_MT_ROUTE_LINK (
	ROUTE_ID VARCHAR(10),
    LINK_SEQ INT,
    LINK_ID VARCHAR(10),
    UPDOWN_DIR VARCHAR(3),
    PRIMARY KEY(ROUTE_ID, LINK_SEQ)
);

CREATE TABLE BIS_HT_BUS_EVENT (
    GPS_DT VARCHAR(16),
    BUS_ID VARCHAR(10),
    IMP_ID VARCHAR(10),
	ROUTE_ID VARCHAR(10),
	LINK_ID VARCHAR(10),
	EVENT_CD VARCHAR(3),
	EVENT_DATA VARCHAR(10),
	EVENT_SEQ SMALLINT,
	RUN_TYPE VARCHAR(3),
	LAT DECIMAL(9,6),
	LON DECIMAL(9,6),
	HEADING SMALLINT,
	SPEED SMALLINT,
	STOP_TM SMALLINT,
	SYS_DT VARCHAR(14),
	PRIMARY KEY(GPS_DT, BUS_ID)
);

CREATE TABLE BIS_IT_LINK_SPEED (
    LINK_ID VARCHAR(10),
	SPEED VARCHAR(10),
	RUN_TIME SMALLINT,
	STOP_TIME SMALLINT,
	UPD_DT VARCHAR(16),
	PRIMARY KEY(LINK_ID)
);

CREATE TABLE BIS_IT_BUS_LOCATION (
    BUS_ID VARCHAR(10),
    IMP_ID VARCHAR(10),
    ROUTE_ID VARCHAR(10),
    NODE_SEQ SMALLINT,
    NODE_ID VARCHAR(10),
    STATION_SEQ SMALLINT,
    STATION_ID VARCHAR(10),
    LINK_ID VARCHAR(10),
    RUN_TYPE VARCHAR(3),
    LAT DECIMAL(9,6),
	LON DECIMAL(9,6),
	GPS_DT VARCHAR(16),
	ALM_TYPE VARCHAR(3) DEFAULT '',
	ALM_DT VARCHAR(16) DEFAULT '',
	SYS_DT VARCHAR(16),
	PRIMARY KEY(BUS_ID)
);

CREATE TABLE BIS_HT_BUS_SERVICE (
    SYS_DT VARCHAR(16),
    BUS_ID VARCHAR(10),
    ROUTE_ID VARCHAR(10),
    PPRV_BUS_ID VARCHAR(10),
    PREV_BUS_ID VARCHAR(10),
    NEXT_BUS_ID VARCHAR(10),
    NNXT_BUS_ID VARCHAR(10),
    PPRV_BUS_NAME VARCHAR(20),
    PPRV_STN_NAME VARCHAR(30),
    PPRV_REL_SEQ SMALLINT,
    PPRV_DIST SMALLINT,
    PPRV_TIME SMALLINT,
    PREV_BUS_NAME VARCHAR(20),
    PREV_STN_NAME VARCHAR(30),
    PREV_REL_SEQ SMALLINT,
    PREV_DIST SMALLINT,
    PREV_TIME SMALLINT,
    NEXT_BUS_NAME VARCHAR(20),
    NEXT_STN_NAME VARCHAR(30),
    NEXT_REL_SEQ SMALLINT,
    NEXT_DIST SMALLINT,
    NEXT_TIME SMALLINT,
    NNXT_BUS_NAME VARCHAR(20),
    NNXT_STN_NAME VARCHAR(30),
    NNXT_REL_SEQ SMALLINT,
    NNXT_DIST SMALLINT,
    NNXT_TIME SMALLINT,
	PRIMARY KEY(SYS_DT, BUS_ID)
);

CREATE TABLE BIS_HT_BIT_SERVICE (
    SYS_DT VARCHAR(16),
    BIT_ID VARCHAR(10),
    BUS_ID VARCHAR(10),
    ROUTE_ID VARCHAR(10),
    ROUTE_TYPE VARCHAR(3),
    BUS_TYPE VARCHAR(3),
    ARRIVAL_TYPE VARCHAR(3),
    RUN_TYPE VARCHAR(3),
    BUS_STN_SEQ SMALLINT,
	PRIMARY KEY(SYS_DT, BIT_ID, BUS_ID)
);
