package kr.tracom.platform.launcher.http.handler;

import java.util.HashMap;
import java.util.Map;

public class MimeHandler {
    private static final Map<String, String> mapMimeType = new HashMap<>();

    static {
        mapMimeType.put("ai", "application/postscript");
        mapMimeType.put("aif", "audio/x-aiff");
        mapMimeType.put("aifc", "audio/x-aiff");
        mapMimeType.put("aiff", "audio/x-aiff");
        mapMimeType.put("asc", "text/plain");
        mapMimeType.put("atom", "application/atom+xml");
        mapMimeType.put("au", "audio/basic");
        mapMimeType.put("avi", "video/x-msvideo");
        mapMimeType.put("bcpio", "application/x-bcpio");
        mapMimeType.put("bin", "application/octet-stream");
        mapMimeType.put("bmp", "image/bmp");
        mapMimeType.put("cdf", "application/x-netcdf");
        mapMimeType.put("cgm", "image/cgm");
        mapMimeType.put("class", "application/octet-stream");
        mapMimeType.put("cpio", "application/x-cpio");
        mapMimeType.put("cpt", "application/mac-compactpro");
        mapMimeType.put("csh", "application/x-csh");
        mapMimeType.put("css", "text/css");
        mapMimeType.put("dcr", "application/x-director");
        mapMimeType.put("dif", "video/x-dv");
        mapMimeType.put("dir", "application/x-director");
        mapMimeType.put("djv", "image/vnd.djvu");
        mapMimeType.put("djvu", "image/vnd.djvu");
        mapMimeType.put("dll", "application/octet-stream");
        mapMimeType.put("dmg", "application/octet-stream");
        mapMimeType.put("dms", "application/octet-stream");
        mapMimeType.put("doc", "application/msword");
        mapMimeType.put("docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document");
        mapMimeType.put("dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template");
        mapMimeType.put("docm","application/vnd.ms-word.document.macroEnabled.12");
        mapMimeType.put("dotm","application/vnd.ms-word.template.macroEnabled.12");
        mapMimeType.put("dtd", "application/xml-dtd");
        mapMimeType.put("dv", "video/x-dv");
        mapMimeType.put("dvi", "application/x-dvi");
        mapMimeType.put("dxr", "application/x-director");
        mapMimeType.put("eps", "application/postscript");
        mapMimeType.put("etx", "text/x-setext");
        mapMimeType.put("exe", "application/octet-stream");
        mapMimeType.put("ez", "application/andrew-inset");
        mapMimeType.put("gif", "image/gif");
        mapMimeType.put("gram", "application/srgs");
        mapMimeType.put("grxml", "application/srgs+xml");
        mapMimeType.put("gtar", "application/x-gtar");
        mapMimeType.put("hdf", "application/x-hdf");
        mapMimeType.put("hqx", "application/mac-binhex40");
        mapMimeType.put("htm", "text/html");
        mapMimeType.put("html", "text/html");
        mapMimeType.put("ice", "x-conference/x-cooltalk");
        mapMimeType.put("ico", "image/x-icon");
        mapMimeType.put("ics", "text/calendar");
        mapMimeType.put("ief", "image/ief");
        mapMimeType.put("ifb", "text/calendar");
        mapMimeType.put("iges", "model/iges");
        mapMimeType.put("igs", "model/iges");
        mapMimeType.put("jnlp", "application/x-java-jnlp-file");
        mapMimeType.put("jp2", "image/jp2");
        mapMimeType.put("jpe", "image/jpeg");
        mapMimeType.put("jpeg", "image/jpeg");
        mapMimeType.put("jpg", "image/jpeg");
        mapMimeType.put("js", "application/x-javascript");
        mapMimeType.put("kar", "audio/midi");
        mapMimeType.put("latex", "application/x-latex");
        mapMimeType.put("lha", "application/octet-stream");
        mapMimeType.put("lzh", "application/octet-stream");
        mapMimeType.put("m3u", "audio/x-mpegurl");
        mapMimeType.put("m4a", "audio/mp4a-latm");
        mapMimeType.put("m4b", "audio/mp4a-latm");
        mapMimeType.put("m4p", "audio/mp4a-latm");
        mapMimeType.put("m4u", "video/vnd.mpegurl");
        mapMimeType.put("m4v", "video/x-m4v");
        mapMimeType.put("mac", "image/x-macpaint");
        mapMimeType.put("man", "application/x-troff-man");
        mapMimeType.put("mathml", "application/mathml+xml");
        mapMimeType.put("me", "application/x-troff-me");
        mapMimeType.put("mesh", "model/mesh");
        mapMimeType.put("mid", "audio/midi");
        mapMimeType.put("midi", "audio/midi");
        mapMimeType.put("mif", "application/vnd.mif");
        mapMimeType.put("mov", "video/quicktime");
        mapMimeType.put("movie", "video/x-sgi-movie");
        mapMimeType.put("mp2", "audio/mpeg");
        mapMimeType.put("mp3", "audio/mpeg");
        mapMimeType.put("mp4", "video/mp4");
        mapMimeType.put("mpe", "video/mpeg");
        mapMimeType.put("mpeg", "video/mpeg");
        mapMimeType.put("mpg", "video/mpeg");
        mapMimeType.put("mpga", "audio/mpeg");
        mapMimeType.put("ms", "application/x-troff-ms");
        mapMimeType.put("msh", "model/mesh");
        mapMimeType.put("mxu", "video/vnd.mpegurl");
        mapMimeType.put("nc", "application/x-netcdf");
        mapMimeType.put("oda", "application/oda");
        mapMimeType.put("ogg", "application/ogg");
        mapMimeType.put("pbm", "image/x-portable-bitmap");
        mapMimeType.put("pct", "image/pict");
        mapMimeType.put("pdb", "chemical/x-pdb");
        mapMimeType.put("pdf", "application/pdf");
        mapMimeType.put("pgm", "image/x-portable-graymap");
        mapMimeType.put("pgn", "application/x-chess-pgn");
        mapMimeType.put("pic", "image/pict");
        mapMimeType.put("pict", "image/pict");
        mapMimeType.put("png", "image/png");
        mapMimeType.put("pnm", "image/x-portable-anymap");
        mapMimeType.put("pnt", "image/x-macpaint");
        mapMimeType.put("pntg", "image/x-macpaint");
        mapMimeType.put("ppm", "image/x-portable-pixmap");
        mapMimeType.put("ppt", "application/vnd.ms-powerpoint");
        mapMimeType.put("pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation");
        mapMimeType.put("potx","application/vnd.openxmlformats-officedocument.presentationml.template");
        mapMimeType.put("ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow");
        mapMimeType.put("ppam","application/vnd.ms-powerpoint.addin.macroEnabled.12");
        mapMimeType.put("pptm","application/vnd.ms-powerpoint.presentation.macroEnabled.12");
        mapMimeType.put("potm","application/vnd.ms-powerpoint.template.macroEnabled.12");
        mapMimeType.put("ppsm","application/vnd.ms-powerpoint.slideshow.macroEnabled.12");
        mapMimeType.put("ps", "application/postscript");
        mapMimeType.put("qt", "video/quicktime");
        mapMimeType.put("qti", "image/x-quicktime");
        mapMimeType.put("qtif", "image/x-quicktime");
        mapMimeType.put("ra", "audio/x-pn-realaudio");
        mapMimeType.put("ram", "audio/x-pn-realaudio");
        mapMimeType.put("ras", "image/x-cmu-raster");
        mapMimeType.put("rdf", "application/rdf+xml");
        mapMimeType.put("rgb", "image/x-rgb");
        mapMimeType.put("rm", "application/vnd.rn-realmedia");
        mapMimeType.put("roff", "application/x-troff");
        mapMimeType.put("rtf", "text/rtf");
        mapMimeType.put("rtx", "text/richtext");
        mapMimeType.put("sgm", "text/sgml");
        mapMimeType.put("sgml", "text/sgml");
        mapMimeType.put("sh", "application/x-sh");
        mapMimeType.put("shar", "application/x-shar");
        mapMimeType.put("silo", "model/mesh");
        mapMimeType.put("sit", "application/x-stuffit");
        mapMimeType.put("skd", "application/x-koan");
        mapMimeType.put("skm", "application/x-koan");
        mapMimeType.put("skp", "application/x-koan");
        mapMimeType.put("skt", "application/x-koan");
        mapMimeType.put("smi", "application/smil");
        mapMimeType.put("smil", "application/smil");
        mapMimeType.put("snd", "audio/basic");
        mapMimeType.put("so", "application/octet-stream");
        mapMimeType.put("spl", "application/x-futuresplash");
        mapMimeType.put("src", "application/x-wais-source");
        mapMimeType.put("sv4cpio", "application/x-sv4cpio");
        mapMimeType.put("sv4crc", "application/x-sv4crc");
        mapMimeType.put("svg", "image/svg+xml");
        mapMimeType.put("swf", "application/x-shockwave-flash");
        mapMimeType.put("t", "application/x-troff");
        mapMimeType.put("tar", "application/x-tar");
        mapMimeType.put("tcl", "application/x-tcl");
        mapMimeType.put("tex", "application/x-tex");
        mapMimeType.put("texi", "application/x-texinfo");
        mapMimeType.put("texinfo", "application/x-texinfo");
        mapMimeType.put("tif", "image/tiff");
        mapMimeType.put("tiff", "image/tiff");
        mapMimeType.put("tr", "application/x-troff");
        mapMimeType.put("tsv", "text/tab-separated-values");
        mapMimeType.put("txt", "text/plain");
        mapMimeType.put("ustar", "application/x-ustar");
        mapMimeType.put("vcd", "application/x-cdlink");
        mapMimeType.put("vrml", "model/vrml");
        mapMimeType.put("vxml", "application/voicexml+xml");
        mapMimeType.put("wav", "audio/x-wav");
        mapMimeType.put("wbmp", "image/vnd.wap.wbmp");
        mapMimeType.put("wbmxl", "application/vnd.wap.wbxml");
        mapMimeType.put("wml", "text/vnd.wap.wml");
        mapMimeType.put("wmlc", "application/vnd.wap.wmlc");
        mapMimeType.put("wmls", "text/vnd.wap.wmlscript");
        mapMimeType.put("wmlsc", "application/vnd.wap.wmlscriptc");
        mapMimeType.put("wrl", "model/vrml");
        mapMimeType.put("xbm", "image/x-xbitmap");
        mapMimeType.put("xht", "application/xhtml+xml");
        mapMimeType.put("xhtml", "application/xhtml+xml");
        mapMimeType.put("xls", "application/vnd.ms-excel");
        mapMimeType.put("xml", "application/xml");
        mapMimeType.put("xpm", "image/x-xpixmap");
        mapMimeType.put("xsl", "application/xml");
        mapMimeType.put("xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        mapMimeType.put("xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template");
        mapMimeType.put("xlsm","application/vnd.ms-excel.sheet.macroEnabled.12");
        mapMimeType.put("xltm","application/vnd.ms-excel.template.macroEnabled.12");
        mapMimeType.put("xlam","application/vnd.ms-excel.addin.macroEnabled.12");
        mapMimeType.put("xlsb","application/vnd.ms-excel.sheet.binary.macroEnabled.12");
        mapMimeType.put("xslt", "application/xslt+xml");
        mapMimeType.put("xul", "application/vnd.mozilla.xul+xml");
        mapMimeType.put("xwd", "image/x-xwindowdump");
        mapMimeType.put("xyz", "chemical/x-xyz");
        mapMimeType.put("zip", "application/zip");
        mapMimeType.put("json", "application/json");
        mapMimeType.put("channel", "application/json");

    };

    public static String getMIMEType(String fileName) {
        if (fileName != null && fileName.length() > 0 ) {
            int pos = fileName.lastIndexOf(".");
            String ext = fileName.substring(pos+1);
            if(mapMimeType.containsKey(ext))
            {
                return mapMimeType.get(ext);
            }
            return "unknown/unknown";
        }
        return "text/html";
    }
}
