DROP TABLE IF EXISTS PLF_MT_SERVICE;
DROP TABLE IF EXISTS PLF_MT_ADMIN;
DROP TABLE IF EXISTS PLF_MT_LAUNCHER;
DROP TABLE IF EXISTS PLF_MT_CHANNEL;
DROP TABLE IF EXISTS PLF_MT_APP;
DROP TABLE IF EXISTS PLF_MT_SCHEDULE;
DROP TABLE IF EXISTS PLF_MT_BACKUP;
DROP TABLE IF EXISTS PLF_MT_LOG;
DROP TABLE IF EXISTS PLF_MT_PARAM;
DROP TABLE IF EXISTS PLF_MT_ROUTING;

DROP TABLE IF EXISTS PLF_MT_FILE_LOG;
DROP TABLE IF EXISTS PLF_HT_SESSION;


DROP TABLE IF EXISTS PLF_MT_SERVER;

DROP TABLE IF EXISTS PLF_IT_SESSION;
DROP TABLE IF EXISTS PLF_IT_STATUS;

DROP TABLE IF EXISTS PLF_IT_DEV_VERSION;

DROP TABLE IF EXISTS PLF_HT_DEV_STATUS;
DROP TABLE IF EXISTS PLF_HT_DEV_CONTROL;

DROP TABLE IF EXISTS PLF_HT_LOG;
DROP TABLE IF EXISTS PLF_HT_TRANSACTION;
DROP TABLE IF EXISTS PLF_HT_FILE_TRANSFER;

CREATE TABLE PLF_MT_ADMIN (
	ADM_ID VARCHAR(10) NOT NULL,
	ADM_NAME VARCHAR(10),
    ADM_LEVEL VARCHAR(10),
	PHONE VARCHAR(50),
	EMAIL VARCHAR(50),
	UPD_DT VARCHAR(16),
	PRIMARY KEY(ADM_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_LAUNCHER (
	PLF_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	IP VARCHAR(20),
	CITY VARCHAR(50),
	LANG_CD VARCHAR(10),
	TIME_ZONE VARCHAR(30),
	DT_FORMAT VARCHAR(30),
	DATE_FORMAT VARCHAR(30),
	TIME_FORMAT VARCHAR(30),
	LOG_CD VARCHAR(10),
	SINCE_DT VARCHAR(16)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_CHANNEL (
	PLF_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	CH_NAME VARCHAR(20),
	CH_PORT INTEGER,
	R_TIMEOUT INTEGER,
	W_TIMEOUT INTEGER,
	HEADER_TYPE VARCHAR(10),
	STR_TYPE VARCHAR(10),
	ENDIAN_TYPE VARCHAR(10),
	PRTL_VER VARCHAR(20),
	INDICATOR INTEGER,
	MAX_SIZE INTEGER,
	MAX_COUNT INTEGER,
	APDU_OFFSET SMALLINT,
	OPT_RC SMALLINT,
	OPT_TO SMALLINT,
	OPT_TR SMALLINT,
	OPT_CE SMALLINT,
	OPT_RF SMALLINT,
	OPT_LF SMALLINT
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_SERVICE (
	SVC_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	SVC_NAME VARCHAR(50),
	VERSION VARCHAR(20),
	ATTRIBUTE VARCHAR(50),
	LAUNCHER VARCHAR(50),
	USE_YN CHAR(1),
	ST_DT VARCHAR(8),
	ED_DT VARCHAR(8)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_SCHEDULE (
	APP_ID VARCHAR(10),
    JOB_CLASS VARCHAR(50),
	JOB_NAME VARCHAR(20),
	JOB_ARGS VARCHAR(20),
	PERIOD VARCHAR(30),
	USE_YN CHAR(1),
	PRIMARY KEY(APP_ID, JOB_CLASS)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_BACKUP (
	APP_ID VARCHAR(10),
    PLF_TB_NAME VARCHAR(30),
	SVC_TB_NAME VARCHAR(30),
	FIELD_LIST VARCHAR(1024),
	BK_TYPE VARCHAR(10),
	BK_PERIOD VARCHAR(5),
	TABLE_KEY VARCHAR(100),
	LINK_MAPPER VARCHAR(30),
	DEL_MAPPER VARCHAR(30),
	SELECT_WHERE VARCHAR(100),
	USE_YN CHAR(1),
	PRIMARY KEY(APP_ID, PLF_TB_NAME)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_FILE_LOG (
	APP_ID VARCHAR(10),
	LOG_NAME VARCHAR(50),
    LOG_PATH VARCHAR(100),
    PRCS_TYPE VARCHAR(10),
	DEL_DAYS SMALLINT,
	USE_YN CHAR(1),
	PRIMARY KEY(APP_ID, LOG_NAME)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_PARAM (
	APP_ID VARCHAR(10),
	PARAM_KEY VARCHAR(30),
    PARAM_VALUE VARCHAR(30),
	REMARK VARCHAR(50),
	USE_YN CHAR(1),
	PRIMARY KEY(APP_ID, PARAM_KEY)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_ROUTING (
    GRP_ID SMALLINT,
    SYS_ID SMALLINT,
    SVC_ID SMALLINT,
    GRP_NAME VARCHAR(20),
	SYS_NAME VARCHAR(20),
	SVC_NAME VARCHAR(20),
	PRIMARY KEY(GRP_ID, SYS_ID, SVC_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_MT_SERVER (
    PLF_ID VARCHAR(10),
    GRP_ID SMALLINT,
	SVR_IP VARCHAR(20),
	SVR_PORT SMALLINT,
	PRTL_TYPE VARCHAR(10),
	USER_ID VARCHAR(20),
	USER_PW VARCHAR(20),
	PRIMARY KEY(PLF_ID, GRP_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_IT_SESSION (
    PLF_ID VARCHAR(10),
	SESSION_ID VARCHAR(10),
	SESSION_NAME VARCHAR(30),
	SESSION_IP VARCHAR(20),
	REMOTE_TYPE VARCHAR(10),
	ELAPSED_TIME INTEGER,
	IN_PACKET INTEGER,
	OUT_PACKET INTEGER,
	LOGIN_DT VARCHAR(16),
	LOGOUT_DT VARCHAR(16),
	LAST_DT VARCHAR(16),
	PRIMARY KEY(PLF_ID, SESSION_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;


CREATE TABLE PLF_HT_SESSION (
    REG_DT VARCHAR(16),
	SESSION_ID VARCHAR(10),
	SESSION_NAME VARCHAR(30),
	SESSION_IP VARCHAR(20),
	ACTION_TYPE VARCHAR(10),
	PRIMARY KEY(REG_DT, SESSION_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_IT_STATUS (
	PLF_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	RUN_DT VARCHAR(16),
	ELAPSED_TIME INTEGER,
	CPU_USAGE VARCHAR(30),
	RAM_USAGE VARCHAR(30),
	HDD_USAGE VARCHAR(30),
	JVM_USAGE VARCHAR(30),
	UPD_DT VARCHAR(16)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_HT_FILE_TRANSFER (
	PLF_ID VARCHAR(10),
	SESSION_ID VARCHAR(10),
	FILE_NAME VARCHAR(50),
	FILE_CD VARCHAR(3),
    SEND_TYPE VARCHAR(3),
    FILE_PATH VARCHAR(50),
	FILE_SIZE INT,
	FILE_POINTER INT,
	SEND_STATE VARCHAR(10),
	SEND_ST_DT VARCHAR(16),
	SEND_ED_DT VARCHAR(16),
	SYS_DT VARCHAR(16),
	PRIMARY KEY(PLF_ID, SESSION_ID, FILE_NAME)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_HT_LOG (
	APP_ID VARCHAR(10) NOT NULL,
	LOG_DT VARCHAR(10) NOT NULL,
	SEQ INTEGER NOT NULL,
	CLASS VARCHAR(100),
	METHOD VARCHAR(100),
	PARAM VARCHAR(1024),
	MESSAGE MEDIUMTEXT,
	SYS_DT VARCHAR(16),
	PRIMARY KEY(APP_ID, SEQ, LOG_DT)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_HT_TRANSACTION (
	REG_DT VARCHAR(16),
	PLF_ID VARCHAR(10),
    SESSION_ID VARCHAR(10),
	PACKET_ID SMALLINT,
	REMOTE_TYPE VARCHAR(10),
	PAYLOAD_TYPE VARCHAR(20),
	ATTR_COUNT SMALLINT,
	ATTR_LIST VARCHAR(256),
	STR_DATA MEDIUMTEXT,
	RETRY_COUNT SMALLINT,
	SEND_STATE VARCHAR(10),
	SEND_DT VARCHAR(16),
	SYS_DT VARCHAR(16),
	PRIMARY KEY(REG_DT, PLF_ID, SESSION_ID, PACKET_ID)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_IT_DEV_VERSION (
    DEVICE_ID VARCHAR(10),
    VERSION_CD VARCHAR(3),
    DEVICE_TYPE SMALLINT,
    VERSION_VALUE VARCHAR(20),
	SYS_DT VARCHAR(16),
	PRIMARY KEY(DEVICE_ID, VERSION_CD)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_HT_DEV_STATUS (
    SYS_DT VARCHAR(16),
    DEVICE_ID VARCHAR(10),
    STATUS_CD VARCHAR(3),
    DEVICE_TYPE SMALLINT,
    STATUS_VALUE SMALLINT,
	PRIMARY KEY(SYS_DT, DEVICE_ID, STATUS_CD)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE PLF_HT_DEV_CONTROL (
    SYS_DT VARCHAR(16),
    DEVICE_ID VARCHAR(10),
    CONTROL_CD VARCHAR(3),
    DEVICE_TYPE SMALLINT,
    CONTROL_VALUE VARCHAR(20),
    CONTROL_RESULT SMALLINT,
	PRIMARY KEY(SYS_DT, DEVICE_ID, CONTROL_CD)
)COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;
